### ISSUE TITLE
VPN Manager and VPN Unlimited

### ISSUE THREAD

**Issue by Huw53** [Zomboided/xbmc.zomboided.plugins#2]
Installed on Raspberry PI3 with libreELEC. The selecting the first vpn connection on set up the add on starts but stops at  "user authentication not used with VPN Unlimited) the prices then stops, and is not connected to VPN. Any help please

**Comment by Zomboided** [comment]
Try 4.1.3.  If that doesn't work, get a log with debug on (see the troubleshooting page on the wiki), and open your issue against the right repo, ie this one https://github.com/Zomboided/service.vpn.manager
